"""
Pre-initialization for FloorPlan203 task.
FloorPlan203 does not need any modifications for the task of putting small valuables in a box.
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='KeyChain|+00.11|+00.45|+04.86',
        position={'x': 0.11291038244962692, 'y': 0.44959357380867004, 'z': 4.855470180511475}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Watch|+00.24|+00.55|+02.52',
        position={'x': 0.2394053339958191, 'y': 0.5507370829582214, 'z': 2.516862392425537}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='RemoteControl|-01.27|+00.45|+03.29',
        position={'x': -1.2715975046157837, 'y': 0.44544124603271484, 'z': 3.294555187225342}
        )
                    
        return event
            