"""
Pre-initialization for FloorPlan207 task.
FloorPlan207 does not need any modifications for the task of putting valuables in a box
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='KeyChain|+01.74|+00.75|+00.76',
        position={'x': 1.7380746603012085, 'y': 0.7534853219985962, 'z': 0.7615025639533997}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Watch|+01.46|+00.75|+00.54',
        position={'x': 1.457930088043213, 'y': 0.7528121471405029, 'z': 0.5416415333747864}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='RemoteControl|+01.51|+00.75|-00.21',
        position={'x': 1.5137279033660889, 'y': 0.7541609406471252, 'z': -0.21295787394046783}
        )
                    
        return event
            