"""
Pre-initialization for FloorPlan226 task.
FloorPlan226 does not need any modifications for the task of putting valuables in a box.
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='KeyChain|-01.16|+00.55|-00.12',
        position={'x': -1.156085729598999, 'y': 0.545421838760376, 'z': -0.12267988920211792}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Watch|-00.25|+00.55|-00.19',
        position={'x': -0.25297650694847107, 'y': 0.545776903629303, 'z': -0.1869911253452301}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='RemoteControl|-00.77|+00.55|-00.17',
        position={'x': -0.7659846544265747, 'y': 0.5457936525344849, 'z': -0.16903585195541382}
        )
                    
        return event
            