"""
Pre-initialization for FloorPlan4 task.
FloorPlan4's faucet and light are turned on
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='ToggleObjectOn',
        objectId='Faucet|-01.37|+01.14|+00.13',
        forceAction=True
        )
                        
        event=controller.step(
        action='ToggleObjectOn',
        objectId='LightSwitch|-02.58|+01.30|+03.50',
        forceAction=True
        )
                        
        return event
            