"""
Pre-initialization for FloorPlan5 task.
FloorPlan5's faucet and light are turned on
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='ToggleObjectOn',
        objectId='Faucet|-00.12|+00.91|-02.26',
        forceAction=True
        )
                        
        event=controller.step(
        action='ToggleObjectOn',
        objectId='LightSwitch|+00.40|+01.30|+02.00',
        forceAction=True
        )
                        
        return event
            