"""
Pre-initialization for FloorPlan2 task.
FloorPlan2's faucet and light are turned on
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='ToggleObjectOn',
        objectId='Faucet|+00.00|+00.91|-01.68',
        forceAction=True
        )
                        
        event=controller.step(
        action='ToggleObjectOn',
        objectId='LightSwitch|-00.15|+01.29|+03.70',
        forceAction=True
        )
                        
        return event
            