"""
Pre-initialization for FloorPlan209 task.
FloorPlan209 does not need any modifications for the task of putting small valuables on a sofa
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Laptop|-02.57|+00.58|-02.51',
        position={'x': -2.570798397064209, 'y': 0.5791771411895752, 'z': -2.512434244155884}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Book|-02.53|+00.70|-05.12',
        position={'x': -2.525362968444824, 'y': 0.6999008655548096, 'z': -5.12480354309082}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='RemoteControl|-04.29|+00.33|-02.66',
        position={'x': -4.292991638183594, 'y': 0.3303918242454529, 'z': -2.663956880569458}
        )
                    
        return event
            