"""
Pre-initialization for FloorPlan2 task.
FloorPlan2's lettuce was moved to visible position
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass
        
    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.
    
        Args:
            event: env.event object
            controller: ai2thor.controller object
    
        Returns:
            event: env.event object
        """
    
            # initialization function - autogenerated
    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Bread|+00.26|+00.99|-00.08',
        position={'x': 0.25613734126091003, 'y': 0.9874744415283203, 'z': -0.07600241154432297}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Tomato|+00.17|+00.97|-00.28',
        position={'x': 0.16839563846588135, 'y': 0.974504292011261, 'z': -0.28153562545776367}
        )
                    
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Lettuce|-01.71|+00.82|-00.14',
        position={'x': -0.11696076393127419, 'y': 1.8335982859134674, 'z': 0.46363327503204355}
        )
                    
        return event
            